version: "3.1"

services:
  attendance:
    image: rajagupt/attendance:latest
    container_name: attendance
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./user-data-vol:/app/resources/images:ro
    depends_on:
      - apm-server
      - management
      - mongo
      - user
      - vault
  management:
    image: rajagupt/management:latest
    container_name: management
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mongo
      - broker
      - user
      - apm-server
  user:
    image: rajagupt/user:latest
    container_name: user
    restart: always
    ports:
      - "8083:8080"
    volumes:
      - ./user-data-vol:/app/resources/images
    depends_on:
      - mongo
      - broker
      - apm-server
  reporting:
    image: rajagupt/reporting:latest
    container_name: reporting
    restart: always
    ports:
      - "8084:8080"
    depends_on:
      - mongo
      - broker
      - apm-server
  #  metrics:
  #    image: rajagupt/metrics:latest
  #    container_name: metrics
  #    restart: always
  #    ports:
  #      - "8085:8080"
  #    depends_on:
  #      - mongo
  #      - broker
  admin:
    image: rajagupt/upresent-admin:latest
    container_name: admin
    restart: always
    ports:
      - "80:80"
    depends_on:
      - user
  videoprocessor:
    image: rajagupt/videoprocessor:latest
    container_name: videoprocessor
    restart: always
    ports:
      - "6000:5000"
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - mongo-data-vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8001:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    hostname: zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./zookeeper-logs-vol:/var/lib/zookeeper/log
      - ./zookeeper-data-vol:/var/lib/zookeeper/data
  broker:
    image: confluentinc/cp-enterprise-kafka:5.3.1
    hostname: broker
    container_name: broker
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: "true"
      CONFLUENT_SUPPORT_CUSTOMER_ID: "anonymous"
    volumes:
      - ./kafka-data-vol:/var/lib/kafka/data
  control-center:
    image: confluentinc/cp-enterprise-control-center:5.3.1
    hostname: control-center
    container_name: control-center
    restart: always
    depends_on:
      - zookeeper
      - broker
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "broker:29092"
      CONTROL_CENTER_ZOOKEEPER_CONNECT: "zookeeper:2181"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
  elasticsearch:
    image: elasticsearch:7.6.1
    container_name: elasticsearch
    restart: always
    user: root
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    volumes:
      - ./elastic-data-vol:/usr/share/elasticsearch/data
  kibana:
    image: kibana:7.6.1
    container_name: kibana
    restart: always
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
      - filebeat
      - metricbeat
      - apm-server
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.6.1
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat-data-vol/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - elasticsearch
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.6.1
    container_name: metricbeat
    restart: always
    user: root
    volumes:
      - ./metricbeat-data-vol/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    depends_on:
      - elasticsearch
  apm-server:
    image: docker.elastic.co/apm/apm-server:7.6.1
    container_name: apm-server
    restart: always
    user: apm-server
    command: --strict.perms=false -E output.elasticsearch.hosts=["elasticsearch:9200"]
    volumes:
      - ./apm-data-vol/apm-server.docker.yaml:/usr/share/apm-server/apm-server.yml:ro
    depends_on:
      - elasticsearch
  spark:
    image: bitnami/spark:2
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
  spark-worker-1:
    image: bitnami/spark:2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  spark-worker-2:
    image: bitnami/spark:2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  vault:
    image: vault:1.3.4
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_ADDR=https://0.0.0.0:8200
      - VAULT_SKIP_VERIFY=true
    volumes:
      - ./vault-data-vol/certs:/vault/certs:ro
      - ./vault-data-vol/policies:/vault/policies:ro
      - ./vault-data-vol/config:/vault/config:ro
      - ./vault-data-vol/data:/vault/data:rw
    entrypoint: vault server -config=/vault/config/vault.json
volumes:
  apm-data-vol:
  user-data-vol:
  mongo-data-vol:
  zookeeper-logs-vol:
  zookeeper-data-vol:
  kafka-data-vol:
  elastic-data-vol:
  filebeat-data-vol:
  metricbeat-data-vol:
  vault-data-vol:
